SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 FactionKey "RHS_AFRF"
 m_aEntityCatalogs +{
  SCR_EntityCatalogMultiList "{6C3EF4C7A1D262F0}" : "{6C3EF4C7A1D262F1}Configs/EntityCatalogs/Groups_EntityCatalog_AFRF_SOF.conf" {
  }
 }
}
