SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{65CE44FDF2502CAB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE44FDF98011B1}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE44FD88072023}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6323328FB5180305}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69C223790CAB22D8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE44D07019303F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6323328FBE6D736A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE44D0D02CFC4A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE44D31406A816}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6556535C799A9432}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6556535C7283C1AD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6556535C71C449DD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCE4116E82}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCFC2E9BBB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64E95B086A6F283C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCFAB91C04}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64E95B0800826B2F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCF07A9712}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCCD9A83E7}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{647CCADCCB3D99E6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68B8C2B563810D10}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68B8C2B55D1582A6}" {
     m_bEnabled 0
    }
   }
  }
 }
}