SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{69E2D14575C3CE6B}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{69E2D14575C3CE7D}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{69E2D14575C3CE7E}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{69E2D14575C3CE7F}" {
   m_sCallsign "Viper-6"
  }
  SCR_CallsignInfo "{69E2D14575C3CE78}" {
   m_sCallsign "Viper-1"
  }
  SCR_CallsignInfo "{69E2D14575C38C00}" {
   m_sCallsign "Viper-2"
  }
  SCR_CallsignInfo "{69E2D144BF3BA329}" {
   m_sCallsign "Viper-3"
  }
  SCR_CallsignInfo "{69E2D144BFF45CA9}" {
   m_sCallsign "Viper-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{69E2D14575C38C02}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{69E2D14575C38C3C}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{69E2D14575C34A1B}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}