SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A01}" {
   m_sEntityPrefab "{6C3EF4C7A1D26201}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_FireTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B01}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C01}" {
     m_eSlotTypes 7
    }
    SCR_EntityCatalogAmbientPatrolData "{6C3EF4C7C0009D01}" {
     m_eGroupType FIRETEAM
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A02}" {
   m_sEntityPrefab "{6C3EF4C7A1D26202}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_AssaultSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B02}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C02}" {
     m_eSlotTypes 7
    }
    SCR_EntityCatalogAmbientPatrolData "{6C3EF4C7C0009D02}" {
     m_eGroupType SQUAD_RIFLE
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A03}" {
   m_sEntityPrefab "{6C3EF4C7A1D26203}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_MGTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B03}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C03}" {
     m_eSlotTypes 7
    }
    SCR_EntityCatalogAmbientPatrolData "{6C3EF4C7C0009D03}" {
     m_eGroupType TEAM_MG
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A04}" {
   m_sEntityPrefab "{6C3EF4C7A1D26204}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_ATTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B04}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C04}" {
     m_eSlotTypes 7
    }
    SCR_EntityCatalogAmbientPatrolData "{6C3EF4C7C0009D04}" {
     m_eGroupType TEAM_AT
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A05}" {
   m_sEntityPrefab "{6C3EF4C7A1D26205}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_SniperTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B05}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C05}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A06}" {
   m_sEntityPrefab "{6C3EF4C7A1D26206}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_MedicalTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B06}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C06}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A07}" {
   m_sEntityPrefab "{6C3EF4C7A1D26207}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_BreacherTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B07}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C07}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A08}" {
   m_sEntityPrefab "{6C3EF4C7A1D26208}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_ReconTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B08}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C08}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0009A09}" {
   m_sEntityPrefab "{6C3EF4C7A1D26209}Prefabs/Groups/AFRF_SOF/Group_AFRF_SOF_WeaponsSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0009B09}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0009C09}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}
