SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6C3EF4C7C0000101}" {
   m_sEntityPrefab "{6C3EF4C7A1D26001}Prefabs/Groups/Group_CPO_FireTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000111}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000112}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000102}" {
   m_sEntityPrefab "{6C3EF4C7A1D26002}Prefabs/Groups/Group_CPO_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000121}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000122}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000103}" {
   m_sEntityPrefab "{6C3EF4C7A1D26003}Prefabs/Groups/Group_CPO_MGTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000131}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000132}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000104}" {
   m_sEntityPrefab "{6C3EF4C7A1D26004}Prefabs/Groups/Group_CPO_ATTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000141}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000142}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000105}" {
   m_sEntityPrefab "{6C3EF4C7A1D26005}Prefabs/Groups/Group_CPO_MarksmanTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000151}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000152}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000106}" {
   m_sEntityPrefab "{6C3EF4C7A1D26006}Prefabs/Groups/Group_CPO_MedicTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000161}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000162}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000107}" {
   m_sEntityPrefab "{6C3EF4C7A1D26007}Prefabs/Groups/Group_CPO_SF_Team.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000171}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000172}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000108}" {
   m_sEntityPrefab "{6C3EF4C7A1D26008}Prefabs/Groups/Group_CPO_SF_ReconTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000181}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000182}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6C3EF4C7C0000109}" {
   m_sEntityPrefab "{6C3EF4C7A1D26009}Prefabs/Groups/Group_CPO_WeaponsSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6C3EF4C7C0000191}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6C3EF4C7C0000192}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}
