SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6C3EF4C7C0000300}" {
   m_sIdentifier "Backpacks and Vests"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6C3EF4C7C0000301}" {
     m_sEntityPrefab "{6C3EF4C7A1D25F41}Prefabs/Items/Equipment/Radios/Radio_ANPRC77_CPO.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6C3EF4C7C0000302}" {
       m_eItemType RADIO_BACKPACK
       m_iSupplyCost 50
      }
     }
    }
   }
  }
 }
}
