SCR_EntityCatalogMultiList {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6C3EF4C7D00007D4}" {
   m_sIdentifier "Others"
   m_aEntities {
    SCR_EntityCatalogEntry "{6C3EF4C7D00007D3}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
  }
   }
  }
 }
}
