SCR_CallInSupportContainerConfig {
 m_aCallIns {
  SCR_CallInSupportContainer "{6C3EF4C7A1D263A1}" : "{94C612087EB33D34}Configs/Systems/RHS_CallIn/RHS_CallIn_Blue_CAS_GBU.conf" {
   m_iMinNumberOfSquadMembers 0
   m_aAvialableForFactions {
    "7Cav"
   }
  }
  SCR_CallInSupportContainer "{6C3EF4C7A1D263A2}" : "{E1E1869F832FEB00}Configs/Systems/RHS_CallIn/RHS_CallIn_Blue_Supplies.conf" {
   m_iMinNumberOfSquadMembers 0
   m_aAvialableForFactions {
    "7Cav"
   }
  }
 }
}
