COE_MissionHeader {
 World "{23027A8302DB3141}worlds/7CavCOE/Eden/7Cav_COE2_Everon.ent"
 m_sName "7Cav COE2 - Everon"
 m_sAuthor "7Cav Dev Team"
 m_sDescription "COE2 persistent operations on Everon."
 m_sDetails "COE2 by Kexanone, with the world setup authored by the 7Cav Dev Team and a 7Cav loading screen."
 m_sIcon "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sLoadingScreen "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sPreviewImage "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sGameMode "#AR-CombatScenario_Name"
 m_iPlayerCount 8
 m_bIsSavingEnabled 1
 m_sSaveFileName "7Cav_COE2_Everon"
}