COE_MissionHeader {
 World "{47F6D7364F506C1E}worlds/7CavCOE/Cain/7Cav_COE2_Kolguyev.ent"
 m_sName "7Cav COE2 - Kolguyev"
 m_sAuthor "7Cav Dev Team"
 m_sDescription "COE2 persistent operations on Kolguyev."
 m_sDetails "COE2 by Kexanone, with the world setup authored by the 7Cav Dev Team and a 7Cav loading screen."
 m_sIcon "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sLoadingScreen "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sPreviewImage "{1B3E0BF029439966}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sGameMode "#AR-CombatScenario_Name"
 m_iPlayerCount 8
 m_bIsSavingEnabled 1
 m_sSaveFileName "7Cav_COE2_Kolguyev"
}