SCR_FactionPlayerLoadout : "{6C3EF4C7E0000000}Configs/Loadouts/Loadout_CPO_Base.conf" {
 m_sLoadoutName "Automatic Rifleman"
 m_sLoadoutResource "{6C3EF4C7A1D25F05}Prefabs/Characters/CPO/Character_CPO_AutomaticRifleman.et"
 m_sLoadoutImage "{181C88EDBAAF4897}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MARSOC/MC/Character_RHS_USMC_MARSOC_MC_MG.edds"
}
