SCR_FactionPlayerLoadout : "{6C3EF4C7E0000000}Configs/Loadouts/Loadout_CPO_Base.conf" {
 m_sLoadoutName "Grenadier"
 m_sLoadoutResource "{6C3EF4C7A1D25F04}Prefabs/Characters/CPO/Character_CPO_Grenadier.et"
 m_sLoadoutImage "{574B38BA2BD71B40}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MARSOC/MC/Character_RHS_USMC_MARSOC_MC_GL.edds"
}
