SCR_FactionPlayerLoadout : "{6C3EF4C7E0000000}Configs/Loadouts/Loadout_CPO_Base.conf" {
 m_sLoadoutName "Team Leader"
 m_sLoadoutResource "{6C3EF4C7A1D25F02}Prefabs/Characters/CPO/Character_CPO_TeamLeader.et"
 m_sLoadoutImage "{FA72CBE7DA64ED66}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MARSOC/MC/Character_RHS_USMC_MARSOC_MC_TL.edds"
}
