SCR_FactionPlayerLoadout : "{6C3EF4C7E0000000}Configs/Loadouts/Loadout_CPO_Base.conf" {
 m_sLoadoutName "SF Rifleman"
 m_sLoadoutResource "{6C3EF4C7A1D25F22}Prefabs/Characters/CPO/Character_CPO_SF_Rifleman.et"
 m_sLoadoutImage "{73679DCE436EF063}UI/Textures/EditorPreviews/Characters/Factions/BLUFOR/RHS_USAF/RHS_USAF_USMC_MARSOC/MC/Character_RHS_USMC_MARSOC_MC_Rifleman.edds"
}
