SCR_LoadoutSaveBlackListHolder {
 m_aSaveBlackListItems {
  SCR_LoadoutSaveBlackListItem "{696018EBE5A940E5}" {
   m_sSaveBlackListItem "{D69684663E89D6EC}Prefabs/Items/Equipment/Radios/Radio_ANPRC152A_OLD.et"
  }
 }
}