SCR_FactionPlayerLoadout : "{9ADB52DA8FE508D4}Prefabs/Characters/Cav_Factions/Bravo/Loadouts/Helios/Loadout_B_Platoon_Medic_Helios.conf" {
 m_sLoadoutResource "{18628E1FEB8F60CF}Prefabs/Characters/Cav_Factions/Charlie/C_PltMedic.et"
 m_sAffiliatedFaction "Pioneer"
}