SCR_FactionPlayerLoadout {
 m_sLoadoutName "Machine Gunner"
 m_sLoadoutResource "{54EA78FAF1244E39}Prefabs/Characters/Cav_Factions/Charlie/Charlie_MG.et"
 m_sLoadoutImage "{43EA535E240F0B17}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_AR.edds"
 m_sAffiliatedFaction "Pioneer"
}