SCR_FactionPlayerLoadout {
 m_sLoadoutName "MAAWS Gunner"
 m_sLoadoutResource "{6077F964A500E307}Prefabs/Characters/Cav_Factions/Charlie/Charlie_MAAWS.et"
 m_sLoadoutImage "{278C426C1D3B4C27}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_LAT.edds"
 m_sAffiliatedFaction "Pioneer"
}