SCR_FactionPlayerLoadout {
 m_sLoadoutName "Marksman"
 m_sLoadoutResource "{DA271290E7895745}Prefabs/Characters/Cav_Factions/Charlie/Charlie_DesignatedMarksman.et"
 m_sLoadoutImage "{13AC78F098028758}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Sniper.edds"
 m_sAffiliatedFaction "Pioneer"
}