SCR_AvailableActionsDisplay : "{80CC0413DDBDFCB9}Configs/ControlHints/AvailableActions.conf" {
 m_aActions {
  SCR_AvailableActionContext "{6620DEADBEDA5842}" {
   m_bEnabled 0
   m_iTimeForHide 0
   m_sTag "CAV_HunterKillerSlew"
   m_sAction "CAV_HunterKillerSlew"
   m_sName "Hunter-Killer slew"
  }
  SCR_AvailableActionContext "{6620DEADBEDA5845}" {
   m_bEnabled 0
   m_iTimeForHide 0
   m_sTag "CAV_HunterKillerCancel"
   m_sAction "CAV_HunterKillerCancel"
   m_sName "Hunter-Killer cancel"
  }
 }
}