SCR_MissionHeaderCampaign {
 World "{BD2521BF9C71FE7F}Worlds/FullEveron.ent"
 m_sName "CE: Everon"
 m_sAuthor "Ironbeard"
 m_sDescription "Classic Everon with base Conflict: Escalation features. Shorter antenna radio ranges offer a semi-linear front line."
 m_sDetails "Capture 6 of 7 objectives to win. Capture points (purple names) are controlled via Capture & Hold zones."
 m_sLoadingScreen "{108B372E84281167}Images/Missions/CE Scenario Full Everon Base.edds"
 m_sPreviewImage "{108B372E84281167}Images/Missions/CE Scenario Full Everon Base.edds"
 m_sGameMode "Conflict: Escalation"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
}