SCR_MissionHeaderCampaign {
 World "{A49CA3C42C4F40F1}Worlds/7Cav_CentralEveronRandomScoring_Centerline.ent"
 m_sName "CE: Central Everon Centerline (Scoring)"
 m_sAuthor "Ironbeard and S3 Dev Team"
 m_sDescription "Advance & Secure through Central Everon with 3 Main objectives across the center of the A.O., using the scoring system. "
 m_sDetails "Capture all 3 objectives or score the most points first. Bases captured will increase your total tickets earned per second."
 m_sIcon "{D623FBCAB74EB0B1}Assets/uMoMe.edds"
 m_sLoadingScreen "{4CFD76B7D34CEF1C}Images/Missions/CE Scenario Central Everon Randomized Scoring.edds"
 m_sPreviewImage "{4CFD76B7D34CEF1C}Images/Missions/CE Scenario Central Everon Randomized Scoring.edds"
 m_sGameMode "Conflict: Escalation"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bSpawnRandomCaches 1
 m_bRandomSpawnpointsEnabled 1
 m_bINDFORCanSpawnOnDistantBases 1
}