SCR_MissionHeaderCampaign {
 World "{57152A9224EB36F0}Worlds/7Cav_BloodinMoni_RHS_WCS.ent"
 m_sName "Blood in the Streets of Monti"
 m_sAuthor "Ironbeard and S3 Dev Team"
 m_sDescription "Advance & Secure the Capture and Hold Zones around Montignac, using the Scoring system. "
 m_sDetails "Capture and hold the lettered Zones around Monti to gain Score. Score the most points first. Bases and Zones captured will increase your team's Score faster."
 m_sIcon "{D623FBCAB74EB0B1}Assets/uMoMe.edds"
 m_sLoadingScreen "{4CFD76B7D34CEF1C}Images/Missions/CE Scenario Central Everon Randomized Scoring.edds"
 m_sPreviewImage "{4CFD76B7D34CEF1C}Images/Missions/CE Scenario Central Everon Randomized Scoring.edds"
 m_sGameMode "Conflict: Escalation"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bSpawnRandomCaches 1
 m_bRandomSpawnpointsEnabled 1
 m_bINDFORCanSpawnOnDistantBases 1
}