SCR_MissionHeaderCampaign {
 World "{CE8DA8A33462DF63}Worlds/CHEStPhilippe.ent"
 m_sName "Capture & Hold Escalation: St. Philippe"
 m_sAuthor "Ironbeard and S3 Dev Team"
 m_sDescription "Smaller scenario for seeders. Conflict: Escalation version of Capture & Hold with Bases & Supply Points"
 m_sDetails "First to score the most points wins. Capture & Hold zones are randomized at the start of each match. Bases earn score as well."
 m_sIcon "{D623FBCAB74EB0B1}Assets/uMoMe.edds"
 m_sLoadingScreen "{D623FBCAB74EB0B1}Assets/uMoMe.edds"
 m_sGameMode "Conflict: Escalation"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bCommanderRoleEnabled 1
}