SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6C3EF4C7C1000001}" {
   m_Info SCR_UIInfo "{6C3EF4C7C1000002}" {
    Name "7Cav"
    Icon "{CCB53AD18A8CCDE8}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_7Cav.edds"
   }
   m_Order 1
   m_LabelType FACTION_CPO_US
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}
