COE_MissionHeader {
 World "{253697A390FBEAC2}worlds/7CavCOE/Kunar/7Cav_COE2_Kunar.ent"
 m_sName "7Cav COE2 - Kunar"
 m_sAuthor "7Cav Dev Team"
 m_sDescription "COE2 persistent operations on Kunar."
 m_sDetails "COE2 by Kexanone, Kunar terrain by KIOK, world setup authored by the 7Cav Dev Team with a 7Cav loading screen."
 m_sIcon "{ED82AC893B55B08B}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sLoadingScreen "{ED82AC893B55B08B}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sPreviewImage "{ED82AC893B55B08B}UI/Textures/MissionLoadingScreens/7Cav_Splash.edds"
 m_sGameMode "#AR-CombatScenario_Name"
 m_iPlayerCount 8
 m_bIsSavingEnabled 1
 m_sSaveFileName "7Cav_COE2_Kunar"
}
