SCR_AvailableActionsDisplay : "{80CC0413DDBDFCB9}Configs/ControlHints/AvailableActions.conf" {
 m_aActions {
  SCR_AvailableActionContext "{6900000400000001}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_DESIGNATE"
   m_sAction "HMD_LaserDesignate"
   m_sName "Toggle laser designator"
  }
  SCR_AvailableActionContext "{6900000400000002}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_CODE_INC"
   m_sAction "HMD_LaserCodeIncrement"
   m_sName "Increase laser code"
  }
  SCR_AvailableActionContext "{6900000400000003}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_CODE_DEC"
   m_sAction "HMD_LaserCodeDecrement"
   m_sName "Decrease laser code"
  }
  SCR_AvailableActionContext "{6900000400000004}" {
   m_bEnabled 0
   m_sTag "HMD_HUD_LASER_VISIBILITY"
   m_sAction "HMD_HUDLaserVisibilityToggle"
   m_sName "Toggle designation HUD visibility"
  }
  SCR_AvailableActionContext "{6900000400000005}" {
   m_bEnabled 0
   m_sTag "HMD_HUD_IFF_MARKERS"
   m_sAction "HMD_HUDIffMarkersToggle"
   m_sName "Toggle IFF and vehicle WP/RP markers"
  }
  SCR_AvailableActionContext "{6900000400000006}" {
   m_bEnabled 0
   m_sTag "HMD_HUD_LASER_MARKING"
   m_sAction "HMD_HUDLaserMarkingToggle"
   m_sName "Toggle vehicle laser marking HUD"
  }
  SCR_AvailableActionContext "{6900000400000007}" {
   m_bEnabled 0
   m_sTag "HMD_VEHICLE_LASER_CODE_INC"
   m_sAction "HMD_VehicleLaserCodeIncrement"
   m_sName "Increase vehicle laser code"
  }
  SCR_AvailableActionContext "{6900000400000008}" {
   m_bEnabled 0
   m_sTag "HMD_VEHICLE_LASER_CODE_DEC"
   m_sAction "HMD_VehicleLaserCodeDecrement"
   m_sName "Decrease vehicle laser code"
  }
  SCR_AvailableActionContext "{6900000400000009}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_REFERENCE_ENTER"
   m_sAction "HMD_LaserReferenceModeToggle"
   m_sName "Enter laser reference mode (WP/RP tools)"
  }
  SCR_AvailableActionContext "{690000040000000A}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_REFERENCE_EXIT"
   m_sAction "HMD_LaserReferenceModeToggle"
   m_sName "Exit laser reference mode"
  }
  SCR_AvailableActionContext "{690000040000000B}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_REFERENCE_PLACE_RP"
   m_sAction "HMD_HUDLaserMarkingToggle"
   m_sName "Place reference marker (RP#)"
  }
  SCR_AvailableActionContext "{690000040000000C}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_REFERENCE_PLACE_WP"
   m_sAction "HMD_VehicleLaserCodeIncrement"
   m_sName "Place waypoint marker (WP#)"
  }
  SCR_AvailableActionContext "{690000040000000D}" {
   m_bEnabled 0
   m_sTag "HMD_LASER_REFERENCE_DELETE"
   m_sAction "HMD_VehicleLaserCodeDecrement"
   m_sName "Delete nearest scoped WP/RP (10m)"
  }
 }
}