SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 m_CallsignInfo SCR_FactionCallsignInfo "{5977478D568C093C}" : "{F4A7AC2FD63074C3}Configs/Callsigns/Callsigns_Viper.conf" {
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{69E2D144ED185C6A}" {
   m_sGroupName "Viper-6"
   m_iGroupSize 3
   m_iRadioFrequency 32200
  }
  SCR_GroupPreset "{69E2D144ECDCEB3D}" {
   m_sGroupName "Viper-1"
   m_iGroupSize 9
   m_iRadioFrequency 33000
  }
  SCR_GroupPreset "{69E2D144EBBB33CC}" {
   m_sGroupName "Viper-2"
   m_iGroupSize 9
   m_iRadioFrequency 33200
  }
  SCR_GroupPreset "{69E2D144EAE9224A}" {
   m_sGroupName "Viper-3"
   m_iGroupSize 9
   m_iRadioFrequency 33400
  }
  SCR_GroupPreset "{69E2D144E9AF7AB6}" {
   m_sGroupName "Viper-4"
   m_iGroupSize 9
  }
 }
 m_bCanAIMarkTargets 0
 m_bCreateOnlyPredefinedGroups 1
 m_iFactionRadioFrequency 32000
}